---
- name: Display Role Details.
  debug:
    msg:
      - '===================================================================='
      - '{{ cookiecutter.author }}.{{ cookiecutter.project }}'
      - '{{ cookiecutter.description }}.'
      - '===================================================================='
