---
dependency:
  name: galaxy
driver:
  name: docker
lint: flake8
platforms:
  - name: bionic
    image: ubuntu:18.04
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
