---
language: python

python:
  - '3.7'

matrix:
  include:
    - os: linux
      dist: xenial

before_install:
  - sudo apt purge ansible
  - sudo apt update

install:
  - sudo apt install -y python3-pip python3-setuptools
  - sudo python3 -m pip install --upgrade pip setuptools wheel
  - sudo python3 -m pip install ansible molecule[docker]

script:
  - python3 -m molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
